version: '3'

services:
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    privileged: true
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900" # VNC server port for viewing the browser
    environment:
      - VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=120
    volumes:
      - ./browser_profile:/home/seluser/browser_profile
    networks:
      - chapito-network

  chapito:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - chrome
    ports:
      - "5001:5001"
    volumes:
      - ./browser_profile:/app/browser_profile
    environment:
      - REMOTE_CHROME_HOST=chrome
      - REMOTE_CHROME_PORT=4444
    networks:
      - chapito-network
    command: python main.py --host 0.0.0.0 --use-browser-profile --verbosity 3

networks:
  chapito-network:
    driver: bridge